//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Timelis.rc
//
#define IDADDNEW                        3
#define IDDELETE                        4
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_TIMESHTYPE                  129
#define IDI_TRAY2                       130
#define IDR_RCLICK                      131
#define IDD_VIEWMONTHLY                 132
#define IDD_MAIN2                       134
#define IDD_MAIN                        135
#define IDD_TASKS                       136
#define IDD_EDITTASK                    137
#define IDR_REPORT_HTML                 138
#define IDD_MANAGE                      139
#define IDD_REPORTING                   140
#define IDD_PAUSES                      141
#define IDD_ADDPAUSE                    142
#define IDD_NEWDAY                      143
#define IDI_TRAY                        145
#define IDD_ADDPROJECT                  146
#define IDD_DELPROJECT                  147
#define IDD_STATS                       148
#define IDD_SELECTACTIVITIES            149
#define IDD_SYNCHRONIZE                 150
#define IDD_OPTIONS                     151
#define IDD_WAIT                        152
#define IDD_PROJECTS                    153
#define IDD_EVENTS                      157
#define IDD_EDITEVENT                   158
#define IDD_SHOWEVENT                   159
#define IDC_RADIO_START                 1001
#define IDC_RADIO_FINISH                1002
#define IDC_RADIO_PAUSE                 1003
#define IDC_DATE                        1004
#define IDC_TIME                        1005
#define IDC_RADIO_ACTIVITIES            1006
#define IDC_MONTH                       1007
#define IDC_INFO                        1007
#define IDC_VIEW                        1008
#define IDC_DATELABEL                   1008
#define IDC_TIMELABEL                   1009
#define IDC_BUTSHOW                     1010
#define IDC_TASKS                       1010
#define IDC_ADDTASK                     1011
#define IDC_EDITTASK                    1012
#define IDC_DELETETASK                  1013
#define IDC_TOTALTASKTIME               1014
#define IDC_UNALLOCTIME                 1015
#define IDC_DAYSTART                    1016
#define IDC_DAYSOFAR                    1017
#define IDC_FINISHED                    1018
#define IDC_FINISHEDLABEL               1019
#define IDC_PROJECTS                    1020
#define IDC_DESCRIPTION                 1021
#define IDC_OFFICIALDESCRIPTION         1021
#define IDC_PRIVATEDESCRIPTION          1022
#define IDC_FINISHEDTIMELABEL           1023
#define IDC_TIME_LABEL                  1024
#define IDC_FILTER_MONTH                1025
#define IDC_FILTER_PERIOD               1026
#define IDC_PERIOD_FROM                 1028
#define IDC_PERIOD_TO                   1029
#define IDC_DAYS                        1030
#define IDC_DAYDATE                     1032
#define IDC_SEARCH                      1034
#define IDC_DAY_FULL                    1036
#define IDC_DAY_HALF                    1037
#define IDC_DAY_NOTSET                  1038
#define IDC_DAYSET                      1039
#define IDC_DAY_ZERODAY                 1040
#define IDC_DELTASK                     1042
#define IDC_NEWDAY                      1043
#define IDC_SHOWACTUALDURATION          1044
#define IDC_DELDAY                      1044
#define IDC_VIEWREPORT                  1045
#define IDC_LOCATION                    1046
#define IDC_REPORTDIR                   1046
#define IDC_DURATION                    1047
#define IDC_CONTRACTOR                  1047
#define IDC_TEMPLATEDIR                 1047
#define IDC_STAT_TOTALDAYS              1048
#define IDC_STAT_ACTUALHOURS            1049
#define IDC_DAY_CUSTOM                  1050
#define IDC_DAY_CUSTOMVALUE             1051
#define IDC_PAUSES                      1052
#define IDC_LABEL                       1053
#define IDC_FROM                        1054
#define IDC_TO                          1055
#define IDC_LENGTH                      1055
#define IDC_SENDALL_TO                  1055
#define IDC_SAVEONLY                    1060
#define IDC_SAVEVIEW                    1061
#define IDC_NAME                        1061
#define IDC_VIEWONLY                    1062
#define IDC_SCHEDULE                    1063
#define IDC_BUTSTARTFINISH              1064
#define IDC_BUTPAUSERESUME              1065
#define IDC_BUTTASKS                    1066
#define IDC_SHOWSTATS                   1070
#define IDC_FILTER_ALLACTIVITIES        1071
#define IDC_FILTER_SELACTIVITIES        1072
#define IDC_SELECTACTIVITIES            1073
#define IDC_BUTMANAGE                   1074
#define IDC_ACTIVITIES                  1075
#define IDC_BUTREPORTING                1075
#define IDC_GETPROJECTS                 1076
#define IDC_SENDTIMESHEET               1077
#define IDC_SEND_NEW                    1078
#define IDC_SEND_ALL                    1079
#define IDC_SENDALL_FROM                1081
#define IDC_SYNC_WSDL                   1082
#define IDC_SYNC_USERNAME               1083
#define IDC_COPYRIGHT                   1084
#define IDC_MESSAGE                     1085
#define IDC_ADDPROJECT                  1088
#define IDC_DELPROJECT                  1089
#define IDC_ADDACTIVITY                 1090
#define IDC_DELACTIVITY                 1091
#define IDC_ENABLEACTIVITY              1092
#define IDC_RENPROJECT                  1093
#define IDC_SHOWDISABLEDACTIVITIES      1093
#define IDC_RENACTIVITY                 1094
#define IDC_SAVE                        1094
#define IDC_MONTH_YEAR                  1096
#define IDC_MONTH_NAME                  1097
#define IDC_TEMPLATES                   1098
#define IDC_MONTH_NAMES                 1099
#define IDC_PAUSE_FROM                  1100
#define IDC_PAUSE_UNTIL                 1101
#define IDC_BUTADDTASK                  1102
#define IDC_TASK_FROM                   1103
#define IDC_TASK_UNTIL                  1104
#define IDC_BUTPAUSES                   1106
#define IDC_DAY_UNTIL                   1107
#define IDC_DAY_FROM                    1108
#define IDC_DAY_LABEL                   1109
#define IDC_REPORTING                   1110
#define IDC_MANAGE                      1111
#define IDC_ADD                         1112
#define IDC_EVENT_DATE                  1113
#define IDC_MODIFY                      1113
#define IDC_EVENT_TEXT                  1114
#define IDC_DELETE                      1114
#define IDC_EVENTS                      1115
#define IDC_EVENT_TIME                  1117
#define IDC_TEXT                        1119
#define IDC_RESCHEDULE_DATE             1122
#define IDC_SNOOZE_TIME                 1123
#define IDC_RESCHEDULE_TIME             1124
#define IDC_RESCHEDULE                  1125
#define IDC_SNOOZE                      1126
#define ID_POPUPRCLICK_ABOUT            32771
#define ID_POPUPRCLICK_EXIT             32772
#define ID_POPUPRCLICK_REPORTING        32775
#define ID_POPUPRCLICK_MANAGING         32778
#define ID_POPUPRCLICK_REOPENDAY        32779
#define ID_POPUPRCLICK_OPTIONS_ADDPROJECT 32781
#define ID_POPUPRCLICK_OPTIONS_DELETEPROJECT 32782
#define ID_POPUPRCLICK_STATISTICS       32784
#define ID_POPUPRCLICK_SYNCHRONIZE      32785
#define ID_POPUPRCLICK_OPTIONS          32786
#define ID_POPUPRCLICK_OPTIONS_PROJECTS 32788
#define ID_POPUPRCLICK_EVENTS           32789
#define ID_POPUPRCLICK_ADDEVENT         32790
#define IDS_TRAYTIP                     61204

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1127
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
